export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST';

export const ADD_TO_CART = 'ADD_TO_CART';
export const DELETE_FROM_CART = 'DELETE_FROM_CART';

export const enum ActionType {
   ADD_TO_WISHLIST = 'ADD_TO_WISHLIST',
   DELETE_FROM_WISHLIST = 'DELETE_FROM_WISHLIST',

   ADD_TO_CART = 'ADD_TO_CART',
   DELETE_FROM_CART = 'DELETE_FROM_CART',
}

export default ActionType;
